version: "3.8"

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  app:
    image: nwaekwudavid/evently:1.2
    container_name: event-management
    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - rabbitmq

    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
      RABBITMQ_URL: ${RABBITMQ_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
      ENCRYPTOR_SECRET_KEY: ${ENCRYPTOR_SECRET_KEY}

    volumes:
      - .:/usr/src/app

    command: npm start

volumes:
  rabbitmq-data:
  postgres-data:
